package com.alain.puntocoma.model.impl;

import com.alain.puntocoma.model.Tutorial;
import com.alain.puntocoma.service.TutorialLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Tutorial service. Represents a row in the &quot;PC_Tutorial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TutorialImpl}.
 * </p>
 *
 * @author Alain
 * @see TutorialImpl
 * @see com.alain.puntocoma.model.Tutorial
 * @generated
 */
public abstract class TutorialBaseImpl extends TutorialModelImpl
    implements Tutorial {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tutorial model instance should use the {@link Tutorial} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TutorialLocalServiceUtil.addTutorial(this);
        } else {
            TutorialLocalServiceUtil.updateTutorial(this);
        }
    }
}
