package com.alain.puntocoma.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Catalogo service. Represents a row in the &quot;PC_Catalogo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.puntocoma.model.impl.CatalogoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.puntocoma.model.impl.CatalogoImpl}.
 * </p>
 *
 * @author Alain
 * @see Catalogo
 * @see com.alain.puntocoma.model.impl.CatalogoImpl
 * @see com.alain.puntocoma.model.impl.CatalogoModelImpl
 * @generated
 */
public interface CatalogoModel extends BaseModel<Catalogo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a catalogo model instance should use the {@link Catalogo} interface instead.
     */

    /**
     * Returns the primary key of this catalogo.
     *
     * @return the primary key of this catalogo
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this catalogo.
     *
     * @param primaryKey the primary key of this catalogo
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the catalogo ID of this catalogo.
     *
     * @return the catalogo ID of this catalogo
     */
    public long getCatalogoId();

    /**
     * Sets the catalogo ID of this catalogo.
     *
     * @param catalogoId the catalogo ID of this catalogo
     */
    public void setCatalogoId(long catalogoId);

    /**
     * Returns the title of this catalogo.
     *
     * @return the title of this catalogo
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this catalogo.
     *
     * @param title the title of this catalogo
     */
    public void setTitle(String title);

    /**
     * Returns the image of this catalogo.
     *
     * @return the image of this catalogo
     */
    @AutoEscape
    public String getImage();

    /**
     * Sets the image of this catalogo.
     *
     * @param image the image of this catalogo
     */
    public void setImage(String image);

    /**
     * Returns the description of this catalogo.
     *
     * @return the description of this catalogo
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this catalogo.
     *
     * @param description the description of this catalogo
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.alain.puntocoma.model.Catalogo catalogo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.alain.puntocoma.model.Catalogo> toCacheModel();

    @Override
    public com.alain.puntocoma.model.Catalogo toEscapedModel();

    @Override
    public com.alain.puntocoma.model.Catalogo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
