package com.alain.puntocoma.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Tutorial service. Represents a row in the &quot;PC_Tutorial&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.alain.puntocoma.model.impl.TutorialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.alain.puntocoma.model.impl.TutorialImpl}.
 * </p>
 *
 * @author Alain
 * @see Tutorial
 * @see com.alain.puntocoma.model.impl.TutorialImpl
 * @see com.alain.puntocoma.model.impl.TutorialModelImpl
 * @generated
 */
public interface TutorialModel extends BaseModel<Tutorial> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tutorial model instance should use the {@link Tutorial} interface instead.
     */

    /**
     * Returns the primary key of this tutorial.
     *
     * @return the primary key of this tutorial
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this tutorial.
     *
     * @param primaryKey the primary key of this tutorial
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the article ID of this tutorial.
     *
     * @return the article ID of this tutorial
     */
    public long getArticleId();

    /**
     * Sets the article ID of this tutorial.
     *
     * @param articleId the article ID of this tutorial
     */
    public void setArticleId(long articleId);

    /**
     * Returns the catalogo ID of this tutorial.
     *
     * @return the catalogo ID of this tutorial
     */
    public long getCatalogoId();

    /**
     * Sets the catalogo ID of this tutorial.
     *
     * @param catalogoId the catalogo ID of this tutorial
     */
    public void setCatalogoId(long catalogoId);

    /**
     * Returns the title of this tutorial.
     *
     * @return the title of this tutorial
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this tutorial.
     *
     * @param title the title of this tutorial
     */
    public void setTitle(String title);

    /**
     * Returns the image of this tutorial.
     *
     * @return the image of this tutorial
     */
    @AutoEscape
    public String getImage();

    /**
     * Sets the image of this tutorial.
     *
     * @param image the image of this tutorial
     */
    public void setImage(String image);

    /**
     * Returns the description of this tutorial.
     *
     * @return the description of this tutorial
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this tutorial.
     *
     * @param description the description of this tutorial
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.alain.puntocoma.model.Tutorial tutorial);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.alain.puntocoma.model.Tutorial> toCacheModel();

    @Override
    public com.alain.puntocoma.model.Tutorial toEscapedModel();

    @Override
    public com.alain.puntocoma.model.Tutorial toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
